apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: changeme
spec:
  secretTemplates:
    - name: aws-credentials
      labels:
        app: elasticsearch-restore-s3-secret
      stringData:
        AWS_ACCESS_KEY_ID: changeme
      data:
        AWS_SECRET_ACCESS_KEY: changeme