apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: changeme
spec:
    secretTemplates:
        - name: aws-credentials
          labels:
            app: elasticsearch-restore-s3-secret
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YUUlrp7BQvQqK3UrJiWINC3oS+w=,iv:8I/URT3v8IA7jzeaLwrOj1KXCMJlpZ6++qR4nEBG46U=,tag:HyGaaMskjWW39R80825ieg==,type:str]
          data:
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FrSLvyxH0A0PZmxyTKWMRRuf8XVygSknLixHLB/HIIh7m7rkgxk0t7cLeoRyr3P11fhnZw==,iv:lzE8RifUfmfmA1Hud84LN/Ejd2b8egFUQNCkr0q9IJA=,tag:799zTMyXE4N6yaho4+m2Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAramRKSFpJTk5pUnpzbFBP
            ZVZUSUZqc3l6bjhKNTJIM0pFVzRXVkJUZXhjCmtEdTh2TllHZDE3TGdnMFB4NDJE
            MWlweDNCcnNMd2ozV2FtaUJ0ZU05am8KLS0tIHI5T21EWXRWTmgzazNkOWdYVGph
            NDlQbHFCTWFqVk92N0J6RExOd0hhdkEK7Da7QHD6ny2mWrmWptSs9U3Yrr0ydvDi
            zvPdeTCNjD4PRa0rQJFtyGjFzqFAeWA217sKs7hatgj8XlWR1KvOsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T17:23:56Z"
    mac: ENC[AES256_GCM,data:GHL4zSXchiXbAe8en6hitLXRicX8egwcz7IQTq2UwM2yvtaTNGLH0fyWU2964UV0VlrkQ+aDgP94E+wGCzOFS69OzB7VTJM8cWSC0H6xwm+1p/GI4bdXTotYC6DiTXnW6oUemuX3SU2fnfdr51N4AJb6SsoTOogc0nUbyD6XOTw=,iv:/9pk5c1ec/AsLnkZ7W/cQuzFXB2it98dF51TK3GAvBU=,tag:ClJI5NtPyzz9INr1yATWVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
