# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
restoreJob:
  enabled: true
  image:
    repository: docker.io/bitnami/elasticsearch
    tag: "7.17.24-debian-12-r2"
  snapshot:
    repository: "s3_repository" # Le nom du repository
  elasticsearch:
    host: "http://judilibre-es:9200" # URL de ton cluster Elasticsearch

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
env:
   - name: ELASTIC_NODE
     value: http://judilibre-es:9200
   - name: ELASTIC_INDEX
     value: judilibre_0